version: "3.9"
services:
  crdb:
    image: cockroachdb/cockroach:v24.2.4
    ports:
      - "26257:26257"
      - "8200:8080"
    command: start-single-node --insecure
    volumes:
      - "roach-single:/cockroach/cockroach-data"
volumes:
  roach-single:
